version: 2
jobs:
  build:

    working_directory: ~/pillar-signal-backend # directory where steps will run

    docker: # run the steps with Docker
      - image: circleci/openjdk:8-jdk-browsers

    environment:
      SIGNAL_VERSION: 1.66

    steps:

      - checkout # check out source code to working directory

      - restore_cache: # restore the saved cache after the first run or if `pom.xml` has changed
          key: pillar-signal-backend-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline # gets the project dependencies

      - save_cache: # saves the project dependencies
          paths:
            - ~/.m2
          key: pillar-signal-backend-{{ checksum "pom.xml" }}

      - run: mvn package # run the actual tests

      - store_test_results: # uploads the test metadata from the `target/surefire-reports` directory so that it can show up in the CircleCI dashboard.
          path: target/surefire-reports

      - store_artifacts: # store the uberjar as an artifact
          path: target/TextSecureServer-1.66-bin.tar.gz

      - run: tar -xvzf target/TextSecureServer-1.66-bin.tar.gz
      # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples


workflows:
  version: 2
  build_and_deploy_to_artifactory:
    jobs:
      - build:
          filters:
            branches:
              only:
                - aws-deployed-version
